site_name: My Read Note
site_url: https://maosher.github.io/
nav:
    - Home : index.md
    - Git : git.md
    - C++ : 
        - C++11 : cpp\cpp11.md
    - Golang : 
        - Goroutine : golang\goroutine.md
        - slice_array : golang\slice_array.md
        - defer : golang\defer.md
    - Algorithm :
        - Tree : al\tree.md   
        - Code : al\code.md
    - Network & OS :
        - tcp : no\tcp.md
        - shell : no\shell.md
    - Database :    
        - Database : db\db.md
    - ThirdParty :
        - MessageQueue : third_party\mq.md
    - Links : links.md
    - About : about.md

theme:
  #name: material
  name: readthedocs
