site_name: Read Note
nav:
    - Home : index.md
    - Git : git.md
    - Golang : 
        - chan : golang\chan.md
        - slice_array : golang\slice_array.md
        - defer : golang\defer.md
    - Algorithm :
        - tree : al\tree.md       
    - Links : links.md
    - About : about.md

theme:
  name: material
