site_name: My Read Note
site_url: https://maosher.github.io/
nav:
    - Home : index.md
    - Git : git.md
    - C++ : 
        - C++11 : cpp\cpp11.md
        - Knowledge Point : cpp\knowledge.md
    - Golang : 
        - Goroutine : golang\goroutine.md
        - Defer : golang\defer.md
        - GC : golang\gc.md
        - Feature : golang\feature.md
        - Slice & Array : golang\slice.md
        - Project Experience : golang\experience.md
        - Think About : golang\about.md
    - Algorithm :
        - Tree : al\tree.md   
        - Code : al\code.md
        - SkipList : al\skiplist.md
    - Network & OS :
        - Tools : os\tools.md
        - Tcp : os\tcp.md
        - Linux shell : os\shell.md
        - Memory : os\memory.md
    - Database :    
        - Mysql : db\mysql.md
        - KV : db\kv.md
        - MongoDb : db\mongodb.md
    - ThirdParty :
        - MessageQueue : third_party\mq.md        
    - Game Design :
        - Framework : game\framework.md
        - Map : game\map.md
    - Links : links.md
    - About : about.md

theme:
  #name: material
  name: readthedocs
